name: Publish package to NuGet

on:
  push:
    tags: 
      - 'v*'

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  PROJECT_PATH: src/Dimo.Client/Dimo.Client.csproj
  OUTPUT_PATH: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json

jobs:
    deploy:
        name: 'Deploy'
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
        
          - name: 'Install dotnet'
            uses: actions/setup-dotnet@v1
            with:
              dotnet-version: '8.0.x'

          - name: 'Restore packages'
            run: dotnet restore ${{ env.PROJECT_PATH }}

          - name: 'Build'
            run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

          - name: 'Version'
            id: version
            uses: battila7/get-version-action@v2

          - name: 'Pack'
            run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.OUTPUT_PATH }}

          - name: 'Publish'
            run: dotnet nuget push ${{ env.OUTPUT_PATH }}\*.nupkg -s ${{ env.NUGET_SOURCE_URL }} -k ${{ env.NUGET_API_KEY }}
