name: Publish package to NuGet

on:
  release:
    types: [published]

env:
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  PROJECT_PATH: src/Dimo.Client/Dimo.Client.csproj
  OUTPUT_PATH: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json

jobs:
    deploy:
        name: 'Deploy'
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
        
          - name: 'Install dotnet'
            uses: actions/setup-dotnet@v1
            with:
              dotnet-version: '8.x.x'

          - name: 'Restore packages'
            run: dotnet restore ${{ env.PROJECT_PATH }}

          - name: 'Build'
            run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

          - name: 'Pack'
            run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build --inclure-symbols --output ${{ env.OUTPUT_PATH }}

          - name: 'Publish'
            run: dotnet nuget push ${{ env.OUTPUT_PATH }}/*.nupkg -s ${{ env.NUGET_SOURCE_URL }} -k ${{ env.NUGET_API_KEY }}
